/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Archivo.Configuracion;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Emanuel CB
 */
public class FrmConfiguracionConexion extends javax.swing.JInternalFrame {


    
    Configuracion confi;
    public FrmConfiguracionConexion() {
        initComponents();

        this.setVisible(true);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cajaServidor = new javax.swing.JTextField();
        cajaUsuario = new javax.swing.JTextField();
        boxMotor = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        cajaContraseña1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Constraseña");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(370, 0, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Motor");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Servidor(IP)");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(100, 10, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Usuario");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(230, 10, 100, 20);
        jPanel2.add(cajaServidor);
        cajaServidor.setBounds(100, 40, 100, 30);
        jPanel2.add(cajaUsuario);
        cajaUsuario.setBounds(230, 40, 120, 30);

        boxMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mysql", " " }));
        boxMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMotorActionPerformed(evt);
            }
        });
        jPanel2.add(boxMotor);
        boxMotor.setBounds(10, 40, 80, 30);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar);
        btnGuardar.setBounds(390, 130, 80, 30);

        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar);
        btnBuscar.setBounds(20, 130, 80, 30);
        jPanel2.add(cajaContraseña1);
        cajaContraseña1.setBounds(370, 40, 100, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Configuracion Connection");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 10, 390, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        try {


            if (cajaServidor.getText().isEmpty() || cajaUsuario.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese los datos correspondientes");

            } else {
                String url = String.valueOf(cajaServidor.getText());
                String usuario = String.valueOf(cajaUsuario.getText());//
               confi=new Configuracion();
               confi.conectar2(url, usuario,"");
               //jdbc:mysql://localhost:3306/riteve?useServerPrepStmts=true
               
            }
        } catch (Exception e) {

            System.out.println("error al guardar devido a " + e.getMessage());
            JOptionPane.showMessageDialog(this, "ERROR  DE CONEXION EN VENTANA");

        }

      
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        cajaServidor.setText("");
        cajaUsuario.setText("");
      


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void boxMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMotorActionPerformed
        String box = "com.mysql.jdbc.Driver";

        //"jdbc:mysql://localhost:3306/riteve?useServerPrepStmts=true"
        //"com.mysql.jdbc.Driver","jdbc:mysql://localhost:3306/riteve?useServerPrepStmts=true","root",""

    }//GEN-LAST:event_boxMotorActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked


    }//GEN-LAST:event_btnBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxMotor;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField cajaContraseña1;
    private javax.swing.JTextField cajaServidor;
    private javax.swing.JTextField cajaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
