/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Cita;
import Clases.Vehiculo;
import Controladores.ControladorCitas;
import Controladores.ControladorVehiculos;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Emanuel CB
 */
public class FrmCrearVehiculo extends javax.swing.JInternalFrame {

    private ArrayList<Vehiculo> vehiculos = new ArrayList();
    private Vehiculo vehiculo;
    private ControladorVehiculos ctlv;
    private Cita cita;
    private ControladorCitas ctlc;

    public FrmCrearVehiculo() {

        ctlv = new ControladorVehiculos();
        ctlv = new ControladorVehiculos();
        vehiculo = null;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cajaPlaca = new javax.swing.JTextField();
        cajaMarca = new javax.swing.JTextField();
        cajaAño = new javax.swing.JTextField();
        cajaPropi = new javax.swing.JTextField();
        cajaNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        cajaModelo1 = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("                      DATOS DEL VEHICULO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 80, 368, 34);
        getContentPane().add(lblFecha);
        lblFecha.setBounds(286, 39, 133, 26);

        jLabel5.setText("PLACA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 40, 60, 23);

        jLabel6.setText("MARCA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 70, 70, 30);

        jLabel7.setText("MODELO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 110, 60, 30);

        jLabel8.setText("AÑO");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 170, 60, 20);

        jLabel9.setText("FECHA INSCRIPCION");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 210, 110, 30);

        jLabel10.setText("CEDULA POROPIETARIO");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 260, 130, 20);

        jLabel11.setText("NOMBRE PROPIETARIO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(300, 320, 140, 20);
        getContentPane().add(cajaPlaca);
        cajaPlaca.setBounds(80, 30, 180, 30);
        getContentPane().add(cajaMarca);
        cajaMarca.setBounds(80, 70, 180, 30);
        getContentPane().add(cajaAño);
        cajaAño.setBounds(80, 160, 180, 30);
        getContentPane().add(cajaPropi);
        cajaPropi.setBounds(430, 260, 140, 30);
        getContentPane().add(cajaNombre);
        cajaNombre.setBounds(430, 310, 140, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("    Crear  Vehiculo");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 0, 270, 50);

        btnAgregar.setText("Crear");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(393, 360, 160, 23);
        getContentPane().add(cajaModelo1);
        cajaModelo1.setBounds(80, 110, 180, 30);
        getContentPane().add(txtDate);
        txtDate.setBounds(140, 210, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

       
        if(cajaPlaca.getText().isEmpty()||cajaMarca.getText().isEmpty()||cajaAño.getText().isEmpty()||cajaPropi.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Ingrese los datos respectivos");
            
            
            
            
        }else{
            
            if(txtDate.getCalendar().before(this)){
                JOptionPane.showMessageDialog(null, "La fecha que elegiste ya paso");
                
            }else{
                
                 cita=new Cita();
                 cita.setFecha(this.txtDate.getDate());
               
               
                 
                
            }
            
            
        }
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JTextField cajaAño;
    private javax.swing.JTextField cajaMarca;
    private javax.swing.JTextField cajaModelo1;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaPlaca;
    private javax.swing.JTextField cajaPropi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFecha;
    private com.toedter.calendar.JDateChooser txtDate;
    // End of variables declaration//GEN-END:variables
}
