/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Emanuel CB
 */
public class FrmCrearCitas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCitas
     */
    public FrmCrearCitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cajaId = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtFechaCita = new com.toedter.calendar.JDateChooser();
        comboxtHoraCita = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cajaPlaca = new javax.swing.JTextField();
        cajaMarca = new javax.swing.JTextField();
        txtAño = new com.toedter.calendar.JDateChooser();
        cajaModelo = new javax.swing.JTextField();
        txtFechaIns = new com.toedter.calendar.JDateChooser();
        cajaPropi = new javax.swing.JTextField();
        cajaNombre = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(null);

        jLabel1.setText("ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 152, 33);

        jLabel2.setText("FECHA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 39, 152, 31);

        jLabel3.setText("HORA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 76, 152, 34);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("                      DATOS DEL VEHICULO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(124, 164, 368, 34);
        getContentPane().add(cajaId);
        cajaId.setBounds(60, 0, 117, 30);
        getContentPane().add(lblFecha);
        lblFecha.setBounds(286, 39, 133, 26);
        getContentPane().add(txtFechaCita);
        txtFechaCita.setBounds(60, 40, 120, 25);

        comboxtHoraCita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8 am", "9 am", "10am", "11am ", "12am", "13pm", "14pm", "15pm", "16pm", "17pm" }));
        getContentPane().add(comboxtHoraCita);
        comboxtHoraCita.setBounds(60, 80, 120, 30);

        jLabel5.setText("PLACA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 210, 90, 23);

        jLabel6.setText("MARCA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 250, 70, 30);

        jLabel7.setText("MODELO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 310, 86, 20);

        jLabel8.setText("AÑO");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 360, 60, 20);

        jLabel9.setText("FECHA INSCRIPCION");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 210, 124, 30);

        jLabel10.setText("CEDULA POROPIETARIO");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 260, 130, 20);

        jLabel11.setText("NOMBRE PROPIETARIO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(300, 320, 140, 20);
        getContentPane().add(cajaPlaca);
        cajaPlaca.setBounds(60, 210, 170, 30);
        getContentPane().add(cajaMarca);
        cajaMarca.setBounds(60, 250, 170, 30);
        getContentPane().add(txtAño);
        txtAño.setBounds(60, 350, 170, 30);
        getContentPane().add(cajaModelo);
        cajaModelo.setBounds(60, 300, 170, 30);
        getContentPane().add(txtFechaIns);
        txtFechaIns.setBounds(430, 210, 140, 30);
        getContentPane().add(cajaPropi);
        cajaPropi.setBounds(430, 260, 140, 30);
        getContentPane().add(cajaNombre);
        cajaNombre.setBounds(430, 310, 140, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("    CREAR   CITAS");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(300, 0, 270, 50);

        btnAgregar.setText("AGREGAR");
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(393, 360, 160, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JTextField cajaId;
    private javax.swing.JTextField cajaMarca;
    private javax.swing.JTextField cajaModelo;
    private javax.swing.JTextField cajaNombre;
    private javax.swing.JTextField cajaPlaca;
    private javax.swing.JTextField cajaPropi;
    private javax.swing.JComboBox<String> comboxtHoraCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblFecha;
    private com.toedter.calendar.JDateChooser txtAño;
    private com.toedter.calendar.JDateChooser txtFechaCita;
    private com.toedter.calendar.JDateChooser txtFechaIns;
    // End of variables declaration//GEN-END:variables
}
