package Vistas;

import Archivo.Configuraciones;
import Archivo.PruebaConexion;
import Clases.Usuario;
import Controladores.ControladorUsuarios;
import java.awt.Color;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Emanuel CB
 */
public class FrmPrincipal extends javax.swing.JFrame {

    //Configuraciones confi;
    private Usuario usuario;
    private FrmCrearUsuarios frmAgregar;
    private ControladorUsuarios ctu;
    private String ContraseñaActual;
    
    
  

    private static PruebaConexion conexion = new PruebaConexion();

    public FrmPrincipal() {
        //setExtendedState(FrmPrincipal.MAXIMIZED_BOTH);


        ctu = new ControladorUsuarios();
        initComponents();
        //  setExtendedState(this.MAXIMIZED_BOTH);
       usuario=new Usuario();
       ctu = new ControladorUsuarios();

        this.conexion.getConectar();

        //setLocationRelativeTo(null);
        //setExtendedState(FrmPrincipal.MAXIMIZED_BOTH);
    }

    public void limpiarCaja() {
cajaUsuario.setText("");
      
    }

    public static PruebaConexion getConexion() {
        return conexion;
    }

    public void VerificarConexion() {
        //si en la ventana de configurar no se logra conectar se cierra toda la aplicacion
        if (conexion.getConexion() == null) {
            JOptionPane.showMessageDialog(null, "conexion nula en frame");
            conexion.getConectar();

        } else {

            JOptionPane.showMessageDialog(null, "Toda la conexion esta bien en frame");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        cajaUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        lblCrearUsurio = new javax.swing.JLabel();
        lblConfiguracion = new javax.swing.JLabel();
        lblAdministrarTecnicos = new javax.swing.JLabel();
        lblEliminarUsuarios = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cedula Usuario");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblCrearUsurio.setText("Crear  o modificar Usuario");
        lblCrearUsurio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrearUsurioMouseClicked(evt);
            }
        });

        lblConfiguracion.setText("Configurar Conexion");
        lblConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfiguracionMouseClicked(evt);
            }
        });

        lblAdministrarTecnicos.setText("Administrar Tecnicos");
        lblAdministrarTecnicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAdministrarTecnicosMouseClicked(evt);
            }
        });

        lblEliminarUsuarios.setText("Eliminar un Usuario");
        lblEliminarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEliminarUsuariosMouseClicked(evt);
            }
        });

        escritorio.setLayer(cajaUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(btnIngresar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblCrearUsurio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblConfiguracion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblAdministrarTecnicos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblEliminarUsuarios, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addComponent(lblCrearUsurio, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(escritorioLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cajaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btnIngresar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAdministrarTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(103, 103, 103))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnIngresar)
                    .addComponent(cajaUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrearUsurio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdministrarTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEliminarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguracionMouseClicked

        int clickCount = evt.getClickCount();
        lblConfiguracion.setForeground(Color.BLACK);
        if (clickCount == 2) {
            lblConfiguracion.setForeground(Color.YELLOW);
            FrmConfiguracionConexion vistaConfi = new FrmConfiguracionConexion();
            escritorio.add(vistaConfi);
            vistaConfi.show();
        }
    }//GEN-LAST:event_lblConfiguracionMouseClicked

    private void lblCrearUsurioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrearUsurioMouseClicked

        int clickCount = evt.getClickCount();
        lblCrearUsurio.setForeground(Color.BLACK);
        if (clickCount == 2) {
            lblCrearUsurio.setForeground(Color.YELLOW);
            FrmCrearUsuarios vistaCrearUsua = new FrmCrearUsuarios();
            escritorio.add(vistaCrearUsua);
            vistaCrearUsua.show();

        }
    }//GEN-LAST:event_lblCrearUsurioMouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        if (cajaUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese los datos necesarios");

        } else {
            
           // usuario=new Usuario();
          try{
            usuario.setCedula(Integer.parseInt(cajaUsuario.getText()));
            ctu.buscarUsuario(usuario);
            lblNombre.setText(usuario.getNombreUsuario());
              System.out.println(" si se realizo");
            
          }catch(Exception e){
              
              System.out.println("error por"+e.getMessage());
          }
            
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void lblAdministrarTecnicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAdministrarTecnicosMouseClicked
        int clickCount = evt.getClickCount();
        lblAdministrarTecnicos.setForeground(Color.BLACK);
        if (clickCount == 2) {
            lblAdministrarTecnicos.setForeground(Color.YELLOW);
            FrmCrearTecnico frmT = new FrmCrearTecnico();
            escritorio.add(frmT);
            frmT.show();
        }
    }//GEN-LAST:event_lblAdministrarTecnicosMouseClicked

    private void lblEliminarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEliminarUsuariosMouseClicked
        int clickCount = evt.getClickCount();
        lblEliminarUsuarios.setForeground(Color.BLACK);
        if (clickCount == 2) {
            lblEliminarUsuarios.setForeground(Color.YELLOW);
            FrmEliminarUsuario frmeli = new FrmEliminarUsuario();
            escritorio.add(frmeli);
            frmeli.show();
        }
    }//GEN-LAST:event_lblEliminarUsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JTextField cajaUsuario;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdministrarTecnicos;
    private javax.swing.JLabel lblConfiguracion;
    private javax.swing.JLabel lblCrearUsurio;
    private javax.swing.JLabel lblEliminarUsuarios;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
